image: "rust:latest"

stages:
  - build
  - deploy

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

deploy_job:
  stage: deploy
  script:
    - cargo publish --token $CARGO_TOKEN
  only:
    - tags
