[package]
name = "quill-delta"
version = "0.0.1"
authors = ["Admin <sive@web.de>"]
description = "quill.js delta format"
repository = "https://gitlab.com/SimVet/quill-delta"
license = "MIT"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"